wordpress:
    image: wordpress
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=contrasea
    ports:
     - "80:80"
    volumes:
     - ./code:/code
     - ./html:/var/www/html
mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=contrasea
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql